site_name: Solutions Architect - SAA-C03
site_dir: my_site
theme:
  name: material
#  custom_dir: overrides
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - announce.dismiss
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - content.code.select
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    logo: simple/awslambda
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: lime
  nav:
    - Home: 'index.md'
    - Domain 1: 'page1\index.md'
    - Domain 2: 'page2\index.md'

  plugins:
    - typeset:
        enabled: true

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

copyright: |
  Copyright &copy; 2023 Georgette Webb
extra:
  generator: false
  