site_name: Solutions Architect - SAA-C03
site_dir: my_site
site_description: Solutions Architect - SAA-C03
# site_url: #
site_author: Georgette Webb

theme:
  name: material
  #custom_dir: overrides
  favicon: images/favicon.png
  include_sidebar: true
  extra_css:
  - css/custom.css
  - css/responsive.css

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - announce.dismiss
    - navigation.top
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - content.code.select
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    logo: simple/awslambda
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: lime
  nav:
    - Solutions Architect - SAA-C03: 'index.md'
    - Domain 1: 'Domain 1\index.md'
    - Domain 2: 'Domain 2\index.md'
    - Domain 3: 'Domain 3\index.md'
    - Domain 4: 'Domain 4\index.md'
    - Domain 5: 'Domain 5\index.md'
    - Domain 6: 'Domain 6\index.md'
    - Domain 7: 'Domain 7\index.md'

  pages:
    - 404: '404.md'

  plugins:
    - typeset:
        enabled: true

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

copyright: |
  Copyright &copy; 2023 Georgette Webb
extra:
  generator: false
extra_javascript:
  - js/custom.js
  